import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import logo from 'public/logo.png';
import homePic from 'public/home-pic.jpg';
import { BiRightArrowCircle } from 'react-icons/bi';

const Home: NextPage = () => {
  const loremIpsum1 = `Lorem Ipsum is simply dummy text of the printing and typesetting
    industry. Lorem Ipsum has been the industry's standard dummy text
    ever since the 1500s, when an unknown printer took a galley of type
    and scrambled it to make a type specimen book. It has survived not
    only five centuries, but also the leap into electronic typesetting,
    remaining essentially unchanged. It was popularised in the 1960s with
    the release of Letraset sheets containing Lorem Ipsum passages, and
    more recently with desktop publishing software like Aldus PageMaker
    including versions of Lorem Ipsum.`;

  return (
    <div className={styles.container}>
      <Head>
        <title>Trifunovic & Co Law Office - Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta
          name="description"
          content={
            'Members of TC law team have been assisting international ' +
            'and national clients from various industries to establish, ' +
            'build and operate their business in Serbia.'
          }
        ></meta>
      </Head>

      <header>
        <Image // TODO
          src={logo}
          alt="Company logo"
          // layout="fill"
          // objectFit="contain"
        />
        <div>
          <h1>Trifunovic & Co</h1>
          <address>
            Kneza Milosa 10, 11000 Beograd, Srbija <br />
            Tel/Fax
          </address>
          <nav>
            <li>What we do</li>
            <li>News</li>
            <li>Our Team</li>
            <li>Career</li>
            <li>Contact</li>
          </nav>
          <span>Change language (TODO)</span>
          <a href="mailto:office@tclaw.co.rs">office@tclaw.co.rs</a>
        </div>
      </header>

      <main className={styles.main}>
        <div style={{ width: '100%', minHeight: '300px' }}>
          <Image // TODO
            src={homePic}
            alt="Stock photo"
          />
        </div>

        <h2>What we do</h2>

        {Array.from(Array(3).keys()).map((i) => (
          <p key={i}>{loremIpsum1}</p>
        ))}

        {Array.from(Array(8).keys()).map((i) => (
          <WorkAreaCard
            key={i}
            title="asd"
            content={loremIpsum1.substring(0, 60)}
            link="https:www.google.com"
          />
        ))}

        <h2>News</h2>

        <h2>Our Team</h2>

        <h2>Contact</h2>

        <h2>Trifunovic & Co</h2>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

function WorkAreaCard({
  title,
  content,
  link,
}: {
  title: string;
  content: string;
  link: string; // TODO: Url?
}): JSX.Element {
  return (
    <div className="work-area-card" /* style={{ cursor: 'pointer' }} */>
      <h3>{title}</h3>
      <p>{content}</p>
      <a href={link} style={{ float: 'right' }}>
        <BiRightArrowCircle />
      </a>
    </div>
  );
}

function HorizontalRuler(): JSX.Element {
  return <hr style={{ width: '100%' }}></hr>;
}

export default Home;
